packages:
  - name: server
    type: go
    deps:
      - pkg/store/postgres:rice
      - pkg/webui:rice
    argdeps:
      - version
      - commit
      - date
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    env:
      - CGO_ENABLED=0
    config:
      generate: true
      dontTest: true
      buildFlags:
        - -tags
        - server
        - -ldflags
        - -X 'github.com/csweichel/werft/pkg/version.Version=${version}' -X 'github.com/csweichel/werft/pkg/version.Commit=${commit}' -X 'github.com/csweichel/werft/pkg/version.Date=${date}'
  - name: plugin-client-lib
    type: go
    config:
      packaging: library
    srcs:
      - "pkg/plugin/client/*.go"
      - "pkg/plugin/common/*.go"
      - "pkg/filterexpr/*.go"
      - "pkg/reporef/*.go"
      - "pkg/api/**/*.go"
      - "go.mod"
      - "go.sum"
  - name: server-release
    type: docker
    deps:
      - :server
      - plugins:all
    argdeps:
      - version
      - latestOrNext
    config:
      dockerfile: "server.Dockerfile"
      image:
        - csweichel/werft:${version}
        - csweichel/werft:${latestOrNext}
  - name: client-linux-amd64
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    argdeps:
      - version
      - commit
      - date
    config:
      dontTest: true
      buildFlags:
        - -tags
        - client
        - -ldflags
        - -X 'github.com/csweichel/werft/pkg/version.Version=${version}' -X 'github.com/csweichel/werft/pkg/version.Commit=${commit}' -X 'github.com/csweichel/werft/pkg/version.Date=${date}'
  - name: nonesense-darwin
    type: generic
  - name: client-darwin-amd64
    type: go
    deps:
      - :nonesense-darwin
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    argdeps:
      - version
      - commit
      - date
    env:
      - CGO_ENABLED=0
      - GOOS=darwin
      - GOARCH=amd64
    config:
      dontTest: true
      buildFlags:
        - -tags
        - client
        - -ldflags
        - -X 'github.com/csweichel/werft/pkg/version.Version=${version}' -X 'github.com/csweichel/werft/pkg/version.Commit=${commit}' -X 'github.com/csweichel/werft/pkg/version.Date=${date}'
  - name: changelog
    type: generic
    srcs:
      - ".git/**/*"
    config:
      commands:
        # - ["git", "describe", "--exact-match", "HEAD"]
        - - sh
          - -c
          - |
            latest=$(git describe --tags `git rev-list --tags --max-count=1`)
            comparison="$latest..HEAD"
            if [ -z "$latest" ]; then comparison=""; fi
            git log $comparison --oneline --no-merges > changelog.txt
            git rev-parse --abbrev-ref HEAD > version.txt
            curl https://api.github.com/repos/csweichel/werft/compare/refs/tags/$latest...master | jq -r .commits[].author.login | sort | uniq > contributor.txt
            echo "Version: $(cat version.txt)"
            echo Changelog:
            cat changelog.txt
            echo Contributor:
            cat contributor.txt
  - name: release
    type: generic
    deps:
      - :client-darwin-amd64
      - :client-linux-amd64
      - :server-release
      - :changelog
    argdeps:
      - version
    config:
      commands:
        - - sh
          - -c
          - |
            echo "## Server Docker images" >> desc.txt
            echo "<pre>$(cat server-release/imgnames.txt)</pre>" >> desc.txt
            echo >> desc.txt
            echo "## Changelog" >> desc.txt
            cat changelog/changelog.txt >> desc.txt
            echo >> desc.txt
            echo "## Contributor" >> desc.txt
            for i in $(cat changelog/contributor.txt); do
              echo "- [$i](https://github.com/$i)" >> desc.txt
            done
        - ["mkdir", "dist"]
        - ["mv", "client-darwin-amd64/werft", "dist/werft-client-darwin-amd64"]
        - ["mv", "client-linux-amd64/werft", "dist/werft-client-linux-amd64"]
        - ["sh", "-c", "cd dist; for i in $(ls); do echo tar cvvfz $i.tar.gz $i; done | sh"]
        - ["sh", "-c", "curl -L https://github.com/c4milo/github-release/releases/download/v1.1.0/github-release_v1.1.0_linux_amd64.tar.gz | tar xz"]
        - ["sh", "-c", "./github-release csweichel/werft ${version} master \"$(cat desc.txt)\" 'dist/*.tar.gz'"]
  - name: all
    type: generic
    deps:
      - :client-darwin-amd64
      - :client-linux-amd64
      - :server
