apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "werft.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "werft.name" . }}
    helm.sh/chart: {{ include "werft.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  "config.yaml": |
    werft:
      baseURL: {{ .Values.config.baseURL }}
      workspaceNodePathPrefix: {{ .Values.config.workspaceNodePathPrefix }}
    service:
      webReadOnly: {{ .Values.config.webReadOnly }}
      webPort: 8080
      grpcPort: 7777
      prometheusPort: 9500
      pprofPort: 6060
{{- if .Values.config.jobSpecRepos }}
      jobSpecRepos:
{{ toYaml .Values.config.jobSpecRepos | indent 8 }}
{{- end }}
    executor:
      namespace: {{ .Release.Namespace }}
      preperationTimeout: {{ .Values.config.timeouts.perperation | default "10m" }}
      totalTimeout: {{ .Values.config.timeouts.total | default "60m" }}
    storage:
      logsPath: /mnt/logs
      jobsConnectionString: {{ .Values.config.db | default (printf "host=%s-postgresql dbname=%s user=%s password=%s connect_timeout=5 sslmode=disable" .Release.Name .Values.postgresql.postgresqlDatabase .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword) }}
    plugins:
{{- if .Values.repositories.github }}
      - name: "github-repo"
        type:
        - repository
        config:
          privateKeyPath: /mnt/secrets/github-app.pem
          appID: {{ .Values.repositories.github.appID }}
          installationID: {{ .Values.repositories.github.installationID }}
      - name: "github-integration"
        type:
        - integration
        config:
          baseURL: {{ .Values.config.baseURL }}
          webhookSecret: {{ .Values.repositories.github.webhookSecret }}
          privateKeyPath: /mnt/secrets/github-app.pem
          appID: {{ .Values.repositories.github.appID }}
          installationID: {{ .Values.repositories.github.installationID }}
          {{- if .Values.repositories.github.integration }}
{{ toYaml .Values.repositories.github.integration | indent 10 }}
          {{- end }}
{{- end }}
{{- if .Values.config.plugins }}
{{ toYaml .Values.config.plugins | indent 6 }}
{{- end }}