// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth-plugin.proto

package common

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticateRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bed500f36987cebc, []int{0}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticateResponse struct {
	Known                bool              `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"`
	Username             string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bed500f36987cebc, []int{1}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetKnown() bool {
	if m != nil {
		return m.Known
	}
	return false
}

func (m *AuthenticateResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateResponse) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthenticateRequest)(nil), "authplugin.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "authplugin.AuthenticateResponse")
	proto.RegisterMapType((map[string]string)(nil), "authplugin.AuthenticateResponse.MetadataEntry")
}

func init() {
	proto.RegisterFile("auth-plugin.proto", fileDescriptor_bed500f36987cebc)
}

var fileDescriptor_bed500f36987cebc = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2d, 0xc8, 0x29, 0x4d, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02,
	0x09, 0x41, 0x44, 0x94, 0xb4, 0xb9, 0x84, 0x1d, 0x4b, 0x4b, 0x32, 0x52, 0xf3, 0x4a, 0x32, 0x93,
	0x13, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0xf2,
	0xb3, 0x53, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0xa5, 0x8b, 0x8c, 0x5c,
	0x22, 0xa8, 0xaa, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x41, 0xca, 0xb3, 0xf3, 0xf2, 0xcb, 0x21,
	0xca, 0x39, 0x82, 0x20, 0x1c, 0x21, 0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc,
	0x54, 0x09, 0x26, 0xb0, 0x39, 0x70, 0xbe, 0x90, 0x17, 0x17, 0x47, 0x6e, 0x6a, 0x49, 0x62, 0x4a,
	0x62, 0x49, 0xa2, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x9e, 0x1e, 0xc2, 0x59, 0x7a, 0xd8,
	0x6c, 0xd1, 0xf3, 0x85, 0x6a, 0x70, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x82, 0xeb, 0x97, 0xb2, 0xe6,
	0xe2, 0x45, 0x91, 0x12, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x84, 0xba, 0x1d, 0xc4, 0x04, 0x39,
	0xb0, 0x2c, 0x31, 0xa7, 0x14, 0xe6, 0x0e, 0x08, 0xc7, 0x8a, 0xc9, 0x82, 0xd1, 0x28, 0x1b, 0xc5,
	0x4b, 0x99, 0xf9, 0x79, 0x01, 0x60, 0x17, 0x08, 0x05, 0x73, 0xf1, 0x20, 0x3b, 0x42, 0x48, 0x1e,
	0xb7, 0xf3, 0xc0, 0x41, 0x26, 0xa5, 0x40, 0xc8, 0xfd, 0x4a, 0x0c, 0x4e, 0x1c, 0x51, 0x6c, 0xc9,
	0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0x49, 0x6c, 0xe0, 0xa8, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xbe, 0x47, 0x0c, 0xa6, 0x9f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationPluginClient is the client API for AuthenticationPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationPluginClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type authenticationPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationPluginClient(cc grpc.ClientConnInterface) AuthenticationPluginClient {
	return &authenticationPluginClient{cc}
}

func (c *authenticationPluginClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/authplugin.AuthenticationPlugin/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationPluginServer is the server API for AuthenticationPlugin service.
type AuthenticationPluginServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
}

// UnimplementedAuthenticationPluginServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationPluginServer struct {
}

func (*UnimplementedAuthenticationPluginServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}

func RegisterAuthenticationPluginServer(s *grpc.Server, srv AuthenticationPluginServer) {
	s.RegisterService(&_AuthenticationPlugin_serviceDesc, srv)
}

func _AuthenticationPlugin_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationPluginServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authplugin.AuthenticationPlugin/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationPluginServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authplugin.AuthenticationPlugin",
	HandlerType: (*AuthenticationPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthenticationPlugin_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth-plugin.proto",
}
